# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10xMdtrw1fMR0rdOhC0j1Hl08EQhH04FJ
"""

# Basit karbon hesaplama örneği

# Aylık elektrik tüketimi (kWh)
electricity_kwh = 50000

# Türkiye ortalama emisyon faktörü (kg CO2 / kWh)
emission_factor = 0.43

# Karbon emisyonu hesaplama
carbon_emission_kg = electricity_kwh * emission_factor

print("Aylık Karbon Emisyonu (kg CO2):", carbon_emission_kg)
print("Aylık Karbon Emisyonu (ton CO2):", carbon_emission_kg / 1000)

"""# ===============================
# BIOLOT - Karbon Risk Hesaplama
# ===============================

electricity_kwh = 50000
natural_gas_m3 = 10000
carbon_price_eur = 85

electricity_factor = 0.43
natural_gas_factor = 2.1

scope2_kg = electricity_kwh * electricity_factor
scope2_ton = scope2_kg / 1000

scope1_kg = natural_gas_m3 * natural_gas_factor
scope1_ton = scope1_kg / 1000

total_emission = scope1_ton + scope2_ton
financial_risk = total_emission * carbon_price_eur


print("------ BIOLOT KARBON RAPORU ------")
print("Scope 1 (Doğalgaz) Ton CO2:", scope1_ton)
print("Scope 2 (Elektrik) Ton CO2:", scope2_ton)
print("Toplam Emisyon (Ton CO2):", total_emission)
print("Karbon Vergi Riski (€):", financial_risk)

"""



import pandas as pd

file_path = "POWER_Point_Daily_20050101_20250101_040d24N_028d93E_LST.csv"

# Dosyayı satır satır inceleyelim
with open(file_path, "r", encoding="latin1") as f:
    lines = f.readlines()

# İlk 30 satırı yazdır
for i in range(30):
    print(lines[i])

import pandas as pd

file_path = "POWER_Point_Daily_20050101_20250101_040d24N_028d93E_LST.csv"

# Dosyayı satır satır oku
with open(file_path, "r", encoding="latin1") as f:
    lines = f.readlines()

# -END HEADER- satırını bul
start_index = None
for i, line in enumerate(lines):
    if "-END HEADER-" in line:
        start_index = i + 1
        break

# Başlık satırı
header = lines[start_index].split(";")[0].strip()

# Veri satırlarını al (sadece virgüllü kısmı)
data_lines = []
for line in lines[start_index + 1:]:
    clean_part = line.split(";")[0].strip()
    data_lines.append(clean_part)

# DataFrame oluştur
from io import StringIO
csv_data = header + "\n" + "\n".join(data_lines)

df = pd.read_csv(StringIO(csv_data))

# Gerekli kolonları al
df = df[["YEAR", "DOY", "T2M"]]

print(df.head())
print("\nToplam Gün Sayısı:", len(df))
# Soğutma Gün Derecesi (CDD) hesapla
df["CDD"] = df["T2M"].apply(lambda x: max(0, x - 22))

print("\nCDD İlk 10 Gün:")
print(df[["YEAR", "DOY", "T2M", "CDD"]].head(10))

print("\nToplam CDD:", df["CDD"].sum())
# 🌿 Biyolojik yüzey simülasyonu (-2°C)
df["T2M_bio"] = df["T2M"] - 2

# Negatif uçlara karşı koruma (çok soğuk günlerde sorun olmasın)
df["T2M_bio"] = df["T2M_bio"].apply(lambda x: x)

# Biyolojik CDD
df["CDD_bio"] = df["T2M_bio"].apply(lambda x: max(0, x - 22))

# Toplam karşılaştırma
total_cdd_ref = df["CDD"].sum()
total_cdd_bio = df["CDD_bio"].sum()

reduction_ratio = (total_cdd_ref - total_cdd_bio) / total_cdd_ref

print("\nReferans Toplam CDD:", total_cdd_ref)
print("Biyolojik Toplam CDD:", total_cdd_bio)
print("Soğutma Azalış Oranı:", reduction_ratio)

print("------ MİKROKLİMA ANALİZİ ------")

# 1️⃣ Ortalama sıcaklık (NASA verisinden)
avg_temp = df["T2M"].mean()

# 2️⃣ Biyolojik yüzeyin 2°C daha serin olduğu varsayımı
delta_T = 2

# 3️⃣ Literatür katsayısı:
# Her 1°C düşüş HVAC yükünü yaklaşık %3 azaltır
hvac_reduction = delta_T * 0.03

# Güvenlik sınırı (max %10 azaltım)
hvac_reduction = min(hvac_reduction, 0.10)

# 4️⃣ Fabrikanın yıllık elektrik tüketimi (örnek)
total_electricity_kwh = 2500000

# HVAC payı (%30 varsayım)
hvac_share = 0.30

hvac_energy = total_electricity_kwh * hvac_share
saved_energy = hvac_energy * hvac_reduction

print("Ortalama Sıcaklık:", round(avg_temp,2))
print("HVAC Azalış Oranı:", round(hvac_reduction*100,2), "%")
print("Tahmini Enerji Tasarrufu (kWh):", round(saved_energy,2))

print("------ ENERJİ → CO2 DÖNÜŞÜMÜ ------")

saved_energy_kwh = 45000  # Senin çıktın
grid_factor_kg_per_kwh = 0.42  # Türkiye şebeke için varsayım (ister sonra güncelleriz)

saved_co2_kg = saved_energy_kwh * grid_factor_kg_per_kwh
saved_co2_ton = saved_co2_kg / 1000

print("Önlenen CO2 (kg):", round(saved_co2_kg, 2))
print("Önlenen CO2 (ton):", round(saved_co2_ton, 3))

print("------ CO2 → KARBON MALİYETİ (OPSİYONEL) ------")

saved_co2_ton = saved_co2_ton  # bir önceki hücreden geliyor
carbon_price_eur = 85  # örnek ETS fiyatı

avoided_cost_eur = saved_co2_ton * carbon_price_eur

print("Kaçınılan Karbon Maliyeti (€):", round(avoided_cost_eur, 2))

import pandas as pd
import numpy as np

print("BIOLOT Sistem Başlatıldı")

# NASA verisini oku
file_path = "POWER_Point_Daily_20050101_20250101_040d24N_028d93E_LST.csv"

df = pd.read_csv(
    file_path,
    skiprows=17,
    delimiter=","
)

# Sadece gerekli kolonlar
df = df[["YEAR", "DOY", "T2M"]]

# CDD hesapla (Base Temp = 22°C)
df["CDD"] = df["T2M"].apply(lambda x: max(0, x - 22))

print("Toplam Gün Sayısı:", len(df))
print("Toplam CDD:", round(df["CDD"].sum(), 2))

import pandas as pd

file_path = "POWER_Point_Daily_20050101_20250101_040d24N_028d93E_LST.csv"

df = pd.read_csv(
    file_path,
    skiprows=17,
    delimiter=",",
    encoding="latin1",
    engine="python"
)

# Kolon isimlerini temizle (boşluk varsa düzelt)
df.columns = df.columns.str.strip()

# Sadece gerekli kolonları al
df = df[["YEAR", "DOY", "T2M"]]

print(df.head())
print("\nToplam Gün Sayısı:", len(df))

file_path = "POWER_Point_Daily_20050101_20250101_040d24N_028d93E_LST.csv"

# Dosyanın içinden "YEAR,DOY" geçen satırı bulalım
with open(file_path, "r", encoding="latin1", errors="ignore") as f:
    for i, line in enumerate(f):
        if line.strip().startswith("YEAR,DOY"):
            header_line = i
            print("✅ Başlık satırı bulundu:", header_line)
            print("Başlık:", line.strip())
            break

import pandas as pd

df = pd.read_csv(
    file_path,
    skiprows=header_line,   # başlığa kadar atla
    delimiter=",",
    encoding="latin1",
    engine="python"
)

df.columns = df.columns.str.strip()
print("✅ Kolonlar:", df.columns.tolist())
print(df.head())
print("\nToplam satır:", len(df))

df = df[["YEAR", "DOY", "T2M"]]
# Convert 'T2M' column to numeric, coercing errors to NaN
df["T2M"] = pd.to_numeric(df["T2M"], errors='coerce')
# Drop rows where 'T2M' is NaN after conversion to avoid issues
df.dropna(subset=['T2M'], inplace=True)
df["CDD"] = (df["T2M"] - 22).clip(lower=0)
print("Toplam CDD:", round(df["CDD"].sum(), 2))

import pandas as pd

# df zaten okundu varsayıyorum. Eğer df yoksa, önce okuma hücreni çalıştır.

# 1) Kolon adlarını temizle (boşluk/; varsa düzelt)
df.columns = df.columns.astype(str).str.strip()
df.columns = [c.split(";")[0].strip() for c in df.columns]

# 2) Gerekli kolonları seç
df = df[["YEAR", "DOY", "T2M"]].copy()

# 3) T2M string -> numeric temizlik
# - virgüllü ondalık gelirse noktaya çevir
# - sayısal olmayan karakterleri temizle
df["T2M"] = (
    df["T2M"]
    .astype(str)
    .str.replace(",", ".", regex=False)
    .str.replace(r"[^0-9\.\-]+", "", regex=True)
)

df["T2M"] = pd.to_numeric(df["T2M"], errors="coerce")

# 4) Bozuk satırları at (T2M NaN olanlar)
df = df.dropna(subset=["T2M"])

# 5) CDD hesabı
BASE_TEMP = 22.0
df["CDD"] = (df["T2M"] - BASE_TEMP).clip(lower=0)

print(df.head(10))
print("\n✅ T2M tipi:", df["T2M"].dtype)
print("✅ Toplam satır:", len(df))
print("✅ Toplam CDD:", round(df["CDD"].sum(), 2))

# --- 3) Mikroklima -> Enerji -> CO2 -> € ---

# A) Varsayımlar / ayarlar
BASE_TEMP = 22.0

beta = 0.5  # bina elastikiyeti: 0.3 iyi yalıtım, 0.5 standart, 0.8 kötü
hvac_annual_kwh = 750000  # fabrikanın yıllık HVAC elektrik tüketimi (bilmiyorsan şimdilik bu kalsın)

grid_factor_kg_per_kwh = 0.42  # şebeke emisyon faktörü (kg CO2 / kWh) - şimdilik sabit
carbon_price_eur_per_ton = 85   # €/ton - senaryo fiyatı

# B) Referans ve biyolojik senaryo (şimdilik biyolojik senaryo = T2M - delta_T kabulü)
# Not: Senin önceki örneğinde biyolojik CDD'yi düşürmüştün. Burada da aynı mantık:
delta_T = 2.4  # yeşil altyapının dış ortamı düşürmesi varsayımı (°C)

df["T_ref"] = df["T2M"]
df["T_bio"] = df["T2M"] - delta_T

df["CDD_ref"] = (df["T_ref"] - BASE_TEMP).clip(lower=0)
df["CDD_bio"] = (df["T_bio"] - BASE_TEMP).clip(lower=0)

CDD_ref_total = df["CDD_ref"].sum()
CDD_bio_total = df["CDD_bio"].sum()

# C) Soğutma azalış oranı (sıfıra bölünme korumalı)
if CDD_ref_total > 0:
    raw_reduction = (CDD_ref_total - CDD_bio_total) / CDD_ref_total
    cooling_reduction = max(0, raw_reduction)  # negatifse 0
else:
    cooling_reduction = 0

# D) HVAC tasarrufu: dış ortam azalışı * beta * HVAC tüketimi
hvac_saving_kwh = hvac_annual_kwh * cooling_reduction * beta

# E) CO2 ve € karşılığı
avoided_co2_kg = hvac_saving_kwh * grid_factor_kg_per_kwh
avoided_co2_ton = avoided_co2_kg / 1000
avoided_cost_eur = avoided_co2_ton * carbon_price_eur_per_ton

print("------ MİKROKLİMA ANALİZİ (3. ADIM) ------")
print("Referans Toplam CDD:", round(CDD_ref_total, 2))
print("Biyolojik Toplam CDD:", round(CDD_bio_total, 2))
print("Soğutma Azalış Oranı:", round(cooling_reduction, 4))
print("Beta (bina elastikiyeti):", beta)
print("Tahmini HVAC Tasarrufu (kWh/yıl):", round(hvac_saving_kwh, 2))

print("\n------ CO2 → € (OPSİYONEL) ------")
print("Kaçınılan CO2 (ton/yıl):", round(avoided_co2_ton, 3))
print("Kaçınılan Karbon Maliyeti (€ / yıl):", round(avoided_cost_eur, 2))

# Kolon isimlerini kontrol et
print(df.columns)

# T2M tipini kontrol et
print(df["T2M"].dtype)

# Eğer string ise temizle
df["T2M"] = (
    df["T2M"]
    .astype(str)
    .str.replace(",", ".", regex=False)
)

df["T2M"] = pd.to_numeric(df["T2M"], errors="coerce")

# NaN satırları temizle
df = df.dropna(subset=["T2M"])

print("\nTemizlenmiş veri tipi:", df["T2M"].dtype)
print("Ortalama Sıcaklık:", df["T2M"].mean())

from pathlib import Path

in_path = Path("POWER_Point_Daily_20050101_20250101_040d24N_028d93E_LST.csv")
out_path = Path("nasa_clean.csv")

lines_out = []
data_started = False

with in_path.open("r", encoding="latin1", errors="ignore") as f:
    for line in f:
        line = line.strip()
        if not line:
            continue

        # Veri başlangıcını bul
        if line.startswith("YEAR,DOY"):
            data_started = True
            # sadece ';' öncesini al
            left = line.split(";")[0].strip()
            lines_out.append(left)
            continue

        if not data_started:
            continue

        # veri satırları: sadece ';' öncesini al
        left = line.split(";")[0].strip()

        # bazen header sonrasında boş/bozuk satır olur
        if left.count(",") < 2:
            continue

        lines_out.append(left)

out_path.write_text("\n".join(lines_out), encoding="utf-8")

print("✅ Temiz dosya yazıldı:", out_path)
print("✅ Satır sayısı:", len(lines_out))
print("Örnek ilk 3 satır:")
print("\n".join(lines_out[:3]))

import pandas as pd

df = pd.read_csv("nasa_clean.csv")

print(df.columns)
print("Satır:", len(df))
print(df.head())

# T2M sayısal mı?
df["T2M"] = pd.to_numeric(df["T2M"], errors="coerce")
df = df.dropna(subset=["T2M"])

print("\nT2M dtype:", df["T2M"].dtype)
print("Ortalama sıcaklık:", df["T2M"].mean())
print("Min/Max:", df["T2M"].min(), df["T2M"].max())

import numpy as np

print("------ MİKROKLİMA ANALİZİ (FINAL) ------")

# 1️⃣ CDD Hesabı (Base Temp = 22°C)
base_temp = 22

df["CDD"] = np.where(df["T2M"] > base_temp, df["T2M"] - base_temp, 0)

total_cdd_ref = df["CDD"].sum()

print("Toplam Referans CDD:", round(total_cdd_ref,2))


# 2️⃣ Biyolojik Alan Senaryosu (2°C soğutma varsayımı)
cooling_effect = 2

df["T_bio"] = df["T2M"] - cooling_effect
df["CDD_bio"] = np.where(df["T_bio"] > base_temp, df["T_bio"] - base_temp, 0)

total_cdd_bio = df["CDD_bio"].sum()

print("Toplam Biyolojik CDD:", round(total_cdd_bio,2))


# 3️⃣ Soğutma Azalış Oranı
if total_cdd_ref > 0:
    cooling_reduction_ratio = (total_cdd_ref - total_cdd_bio) / total_cdd_ref
else:
    cooling_reduction_ratio = 0

print("Soğutma Azalış Oranı:", round(cooling_reduction_ratio,4))


# 4️⃣ HVAC Enerji Tasarrufu
annual_hvac_consumption = 500000   # fabrikanın yıllık soğutma kWh tüketimi (örnek)
beta = 0.5                         # bina elastikiyeti

hvac_saving_kwh = annual_hvac_consumption * cooling_reduction_ratio * beta

print("Beta (bina elastikiyeti):", beta)
print("Tahmini HVAC Tasarrufu (kWh/yıl):", round(hvac_saving_kwh,2))


# 5️⃣ CO2 Azalışı
electricity_emission_factor = 0.43  # kg CO2/kWh

avoided_co2_ton = (hvac_saving_kwh * electricity_emission_factor) / 1000

print("\n------ CO2 → € (OPSİYONEL) ------")
print("Kaçınılan CO2 (ton/yıl):", round(avoided_co2_ton,3))


# 6️⃣ Karbon Fiyatı
carbon_price_eur = 85

avoided_cost = avoided_co2_ton * carbon_price_eur

print("Kaçınılan Karbon Maliyeti (€ / yıl):", round(avoided_cost,2))

import pandas as pd

NASA_FILE = "POWER_Point_Daily_20050101_20250101_040d24N_028d93E_LST.csv"

# Dosyayı ham olarak oku
df_raw = pd.read_csv(
    NASA_FILE,
    skiprows=17,
    encoding="latin1",
    engine="python"
)

# Sadece virgül öncesi kolonları al ( ; sonrası çöplük kısmı atılır )
df_raw.columns = df_raw.columns.str.split(";").str[0]

# İlk 7 gerçek kolonu seç
df = df_raw.iloc[:, 0:7]

# Kolon isimlerini temizle
df.columns = ["YEAR", "DOY", "T2M", "RH2M", "PRECTOTCORR", "WS2M", "ALLSKY_SFC_SW_DWN"]

# Sayısal dönüşüm
df["T2M"] = pd.to_numeric(df["T2M"], errors="coerce")

print("Satır Sayısı:", len(df))
print("\nKolonlar:", df.columns)
print("\nİlk 5 Satır:")
print(df.head())

print("\nOrtalama Sıcaklık:", df["T2M"].mean())
print("Min / Max:", df["T2M"].min(), "/", df["T2M"].max())
import pandas as pd

NASA_FILE = "POWER_Point_Daily_20050101_20250101_040d24N_028d93E_LST.csv"

df_raw = pd.read_csv(
    NASA_FILE,
    skiprows=17,
    encoding="latin1",
    engine="python"
)

# Kolon adlarını ; sonrası çöpten temizle
df_raw.columns = df_raw.columns.astype(str).str.split(";").str[0]

# İlk 7 gerçek kolon
df = df_raw.iloc[:, 0:7].copy()
df.columns = ["YEAR", "DOY", "T2M", "RH2M", "PRECTOTCORR", "WS2M", "ALLSKY_SFC_SW_DWN"]

# Hücre içi ; çöplerini temizleyen fonksiyon
def clean_cell(x):
    if pd.isna(x):
        return None
    s = str(x)
    s = s.split(";")[0]          # ; varsa ilk parça
    s = s.replace(",", ".")      # , ondalık olursa .
    return s

# Sayısala çevir (hepsini güvene alalım)
for col in ["T2M", "RH2M", "PRECTOTCORR", "WS2M", "ALLSKY_SFC_SW_DWN"]:
    df[col] = df[col].apply(clean_cell)
    df[col] = pd.to_numeric(df[col], errors="coerce")

# Bozuk satırları at (en azından YEAR/DOY/T2M dolu olsun)
df = df.dropna(subset=["YEAR", "DOY", "T2M"]).reset_index(drop=True)

print("Satır Sayısı:", len(df))
print(df.head())

print("\nT2M dtype:", df["T2M"].dtype)
print("Ortalama sıcaklık:", df["T2M"].mean())
print("Min/Max:", df["T2M"].min(), df["T2M"].max())

print("\nALLSKY örnekleri (ilk 5):")
print(df["ALLSKY_SFC_SW_DWN"].head())

import numpy as np

# --- NOSAB ÖRNEK FABRİKA VARSAYIMLARI (değiştirebilirsin) ---
BASE_TEMP = 22.0          # CDD baz sıcaklık
DELTA_T = 2.4             # yeşil altyapı ile dış ortam soğutma etkisi (°C)
BETA = 0.5                # bina elastikiyeti (0.3 iyi, 0.5 normal, 0.8 kötü)

HVAC_KWH_YEAR = 2500000   # fabrikanın yıllık HVAC elektrik tüketimi (kWh/yıl) - örnek
GRID_FACTOR_KG_PER_KWH = 0.43  # şebeke emisyon faktörü (kg CO2 / kWh) - örnek
CARBON_PRICE_EUR = 85.5        # €/ton - örnek

# --- CDD hesapları ---
df2 = df.copy()

# Referans dış sıcaklık = T2M (NASA)
df2["T_ref"] = df2["T2M"]

# Biyolojik senaryo = dış sıcaklık DELTA_T kadar düşsün
df2["T_bio"] = df2["T2M"] - DELTA_T

# CDD hesapla
df2["CDD_ref"] = np.maximum(0, df2["T_ref"] - BASE_TEMP)
df2["CDD_bio"] = np.maximum(0, df2["T_bio"] - BASE_TEMP)

total_cdd_ref = df2["CDD_ref"].sum()
total_cdd_bio = df2["CDD_bio"].sum()

# Sıfıra bölünme koruması
if total_cdd_ref > 0:
    cooling_reduction = (total_cdd_ref - total_cdd_bio) / total_cdd_ref
    cooling_reduction = max(0, cooling_reduction)  # negatif koruma
else:
    cooling_reduction = 0.0

# Beta ile bina içi HVAC etkisi
hvac_reduction = cooling_reduction * BETA

# Yıllık HVAC tasarrufu (kWh)
saved_hvac_kwh = HVAC_KWH_YEAR * hvac_reduction

# CO2 kaçınımı (ton/yıl)
saved_co2_ton = (saved_hvac_kwh * GRID_FACTOR_KG_PER_KWH) / 1000

# € karşılığı
saved_eur = saved_co2_ton * CARBON_PRICE_EUR

# --- RAPOR ---
print("------ MİKROKLİMA ANALİZİ (3. ADIM) ------")
print("Satır sayısı:", len(df2), "(Not: 7306 beklenir, sizde 7302 var -> ilk günler eksik olabilir)")
print("Ortalama T2M (°C):", round(df2["T2M"].mean(), 2))
print("Toplam Referans CDD:", round(total_cdd_ref, 2))
print("Toplam Biyolojik CDD:", round(total_cdd_bio, 2))
print("Soğutma Azalış Oranı:", round(cooling_reduction, 4))
print("Beta (bina elastikiyeti):", BETA)
print("Tahmini HVAC Tasarrufu (kWh/yıl):", round(saved_hvac_kwh, 2))

print("\n------ CO2 → € (OPSİYONEL) ------")
print("Kaçınılan CO2 (ton/yıl):", round(saved_co2_ton, 3))
print("Kaçınılan Karbon Maliyeti (€ / yıl):", round(saved_eur, 2))

# ---- GERÇEKÇİ HVAC MODELİ ----

DELTA_T = 2.4
BETA = 0.5
HVAC_KWH_YEAR = 2500000
GRID_FACTOR_KG_PER_KWH = 0.43
CARBON_PRICE_EUR = 85.5

# 1°C başına %4 enerji azalımı
ENERGY_SENSITIVITY = 0.04

external_energy_effect = DELTA_T * ENERGY_SENSITIVITY
hvac_reduction = external_energy_effect * BETA

saved_hvac_kwh = HVAC_KWH_YEAR * hvac_reduction
saved_co2_ton = (saved_hvac_kwh * GRID_FACTOR_KG_PER_KWH) / 1000
saved_eur = saved_co2_ton * CARBON_PRICE_EUR

print("------ DÜZELTİLMİŞ MİKROKLİMA MODELİ ------")
print("Dış Ortam Enerji Etkisi (%):", round(external_energy_effect*100,2))
print("Gerçek HVAC Azalışı (%):", round(hvac_reduction*100,2))
print("HVAC Tasarrufu (kWh/yıl):", round(saved_hvac_kwh,2))
print("Kaçınılan CO2 (ton/yıl):", round(saved_co2_ton,3))
print("Kaçınılan Karbon Maliyeti (€ / yıl):", round(saved_eur,2))

# ---- NOSAB ÖRNEK FABRİKA (SENARYO VERİLERİ) ----

factory = {
    "name": "NOSAB Örnek Tekstil Fabrikası",
    "area_m2": 20000,

    # Yıllık tüketimler (örnek)
    "electricity_kwh_year": 2500000,     # 2.5 GWh/yıl
    "natural_gas_m3_year": 180000,       # 180k m3/yıl

    # Emisyon faktörleri
    "grid_factor_kg_per_kwh": 0.43,      # kgCO2/kWh
    "gas_factor_kg_per_m3": 2.0,         # kgCO2/m3 (basit yaklaşım)

    # Karbon fiyatı
    "carbon_price_eur_per_ton": 85.5,

    # Su tarafı (örnek)
    "water_baseline_m3_year": 12000,     # sistem yokken
    "water_actual_m3_year": 8000,        # BIOLOT sonrası
    "pump_energy_index_kwh_per_m3": 0.4  # kWh/m3
}

factory

# ---- 1) KARBON MOTORU (Scope 1 + Scope 2) ----
e_kwh = factory["electricity_kwh_year"]
g_m3  = factory["natural_gas_m3_year"]

grid_factor = factory["grid_factor_kg_per_kwh"]
gas_factor  = factory["gas_factor_kg_per_m3"]
carbon_price = factory["carbon_price_eur_per_ton"]

scope2_ton = (e_kwh * grid_factor) / 1000
scope1_ton = (g_m3  * gas_factor)  / 1000

total_ton = scope1_ton + scope2_ton
carbon_risk_eur = total_ton * carbon_price


# ---- 2) MİKROKLİMA (SENİN DÜZELTİLMİŞ MODEL SONUCUN) ----
delta_t = 2.4
beta = 0.5
energy_sensitivity = 0.04  # 1°C başına %4

external_energy_effect = delta_t * energy_sensitivity
hvac_reduction = external_energy_effect * beta

hvac_saved_kwh = e_kwh * hvac_reduction
hvac_saved_co2_ton = (hvac_saved_kwh * grid_factor) / 1000
hvac_saved_eur = hvac_saved_co2_ton * carbon_price


# ---- 3) SU TASARRUFU (Baseline - Actual) + Pompa Enerjisi ----
water_base = factory["water_baseline_m3_year"]
water_act  = factory["water_actual_m3_year"]
pump_idx   = factory["pump_energy_index_kwh_per_m3"]

saved_water_m3 = max(0, water_base - water_act)
water_status = "SUCCESS_SAVINGS" if water_base - water_act >= 0 else "WARNING_EXCESS_CONSUMPTION"

saved_pump_kwh = saved_water_m3 * pump_idx
saved_pump_co2_ton = (saved_pump_kwh * grid_factor) / 1000
saved_pump_eur = saved_pump_co2_ton * carbon_price


# ---- 4) TOPLAM ÖZET ----
total_saved_kwh = hvac_saved_kwh + saved_pump_kwh
total_saved_co2_ton = hvac_saved_co2_ton + saved_pump_co2_ton
total_saved_eur = hvac_saved_eur + saved_pump_eur

print("\n===============================")
print("🏭 BIOLOT YILLIK ÖZET RAPORU")
print("===============================")
print("Fabrika:", factory["name"])
print("Alan (m²):", factory["area_m2"])

print("\n--- KARBON (Scope 1 + Scope 2) ---")
print("Scope 1 (Doğalgaz) ton CO2:", round(scope1_ton, 2))
print("Scope 2 (Elektrik) ton CO2:", round(scope2_ton, 2))
print("Toplam Emisyon ton CO2:", round(total_ton, 2))
print("Karbon Riski (€ / yıl):", round(carbon_risk_eur, 2))

print("\n--- MİKROKLİMA / HVAC ---")
print("Delta T (°C):", delta_t)
print("HVAC Azalışı (%):", round(hvac_reduction*100, 2))
print("HVAC Tasarrufu (kWh/yıl):", round(hvac_saved_kwh, 0))
print("Kaçınılan CO2 (ton/yıl):", round(hvac_saved_co2_ton, 3))
print("Kaçınılan Karbon Maliyeti (€ / yıl):", round(hvac_saved_eur, 2))

print("\n--- SU / POMPA ---")
print("Baseline su (m³/yıl):", water_base)
print("Gerçek su (m³/yıl):", water_act)
print("Durum:", water_status)
print("Kurtarılan su (m³/yıl):", round(saved_water_m3, 0))
print("Pompa enerji tasarrufu (kWh/yıl):", round(saved_pump_kwh, 0))
print("Pompa CO2 kazancı (ton/yıl):", round(saved_pump_co2_ton, 3))
print("Pompa karbon maliyeti kazancı (€ / yıl):", round(saved_pump_eur, 2))

print("\n--- TOPLAM OPERASYONEL KAZANÇ (HVAC + Pompa) ---")
print("Toplam enerji tasarrufu (kWh/yıl):", round(total_saved_kwh, 0))
print("Toplam kaçınılan CO2 (ton/yıl):", round(total_saved_co2_ton, 3))
print("Toplam kaçınılan karbon maliyeti (€ / yıl):", round(total_saved_eur, 2))

# ---- AYLIK NASA ANALİZİ ----

import pandas as pd

# Tarih oluştur
df["DATE"] = pd.to_datetime(df["YEAR"].astype(str) + "-" + df["DOY"].astype(str), format="%Y-%j")

# Ay bilgisi ekle
df["MONTH"] = df["DATE"].dt.month

# Aylık ortalama sıcaklık
monthly_avg = df.groupby("MONTH")["T2M"].mean()

# Aylık CDD
base_temp = 22
df["CDD"] = df["T2M"].apply(lambda x: max(0, x - base_temp))
monthly_cdd = df.groupby("MONTH")["CDD"].sum()

print("------ AYLIK ORTALAMA SICAKLIK (°C) ------")
print(monthly_avg)

print("\n------ AYLIK TOPLAM CDD ------")
print(monthly_cdd)

# ---- AYLIK HVAC TASARRUF MODELİ ----

annual_hvac_consumption = 2500000  # kWh
real_reduction_rate = 0.048        # %4.8

annual_saving = annual_hvac_consumption * real_reduction_rate

# Yıllık toplam CDD
total_cdd_year = monthly_cdd.sum()

# Her ayın CDD oranı
monthly_ratio = monthly_cdd / total_cdd_year

# Aylık enerji tasarrufu
monthly_energy_saving = monthly_ratio * annual_saving

# CO2 hesap
electricity_factor = 0.43  # kg CO2/kWh
carbon_price = 85          # €/ton

monthly_co2_kg = monthly_energy_saving * electricity_factor
monthly_co2_ton = monthly_co2_kg / 1000
monthly_euro = monthly_co2_ton * carbon_price

print("------ AYLIK BIOLOT RAPORU ------")
for month in range(1, 13):
    print(
        f"Ay {month}: "
        f"Tasarruf {monthly_energy_saving.get(month,0):.0f} kWh | "
        f"CO2 {monthly_co2_ton.get(month,0):.2f} ton | "
        f"€ {monthly_euro.get(month,0):.2f}"
    )

